# Generated by Django 5.0.4 on 2024-04-19 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_inventario', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('Comida', 'Comida'), ('Bebida', 'Bebida'), ('Postre', 'Postre')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mesa', models.IntegerField()),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('estadopedido', models.CharField(choices=[('En espera', 'En Espera'), ('Aceptado', 'Aceptado'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado')], max_length=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.articulo')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurante.carrito')),
            ],
        ),
    ]
