# Generated by Django 5.0.4 on 2024-05-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0002_alter_articulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(choices=[('Comida', 1), ('Bebida', 2), ('Postre', 3)], max_length=10),
        ),
    ]
