# Generated by Django 5.0.4 on 2024-05-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0006_alter_articulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(choices=[('a', '1 Comida'), ('b', '2 Bebida'), ('c', ' 3Postre')], max_length=10),
        ),
    ]
