# Generated by Django 5.0.4 on 2024-05-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0009_alter_articulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(choices=[('b', 'Bebida'), ('a', 'Comida'), ('c', 'Postre')], max_length=10),
        ),
    ]
