# Generated by Django 5.0.4 on 2024-05-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0012_alter_articulo_options_alter_articulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(choices=[(1, 'Comida'), (2, 'Bebida'), (3, 'Postre')], max_length=10),
        ),
    ]
