# Generated by Django 5.0.4 on 2024-05-15 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0014_alter_articulo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['tipo']},
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='estadopedido',
        ),
        migrations.AddField(
            model_name='carrito',
            name='estadopedido',
            field=models.CharField(choices=[('SinAceptar', 'SinAceptar'), ('En espera', 'En Espera'), ('Aceptado', 'Aceptado'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado')], default='sinAceptar', max_length=10),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
