# Generated by Django 5.0.4 on 2024-05-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0015_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='pagado',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='estadopedido',
            field=models.CharField(choices=[('SinAceptar', 'SinAceptar'), ('En espera', 'En Espera'), ('Aceptado', 'Aceptado'), ('Terminado', 'Terminado'), ('Entregado', 'Entregado'), ('Pagado', 'Pagado')], default='sinAceptar', max_length=10),
        ),
    ]
